name: flutter_ecom
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  carousel_pro: ^0.0.13

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
    - assets/logo.png
    - assets/pdct.jpg
    - assets/1.png
    - assets/2.png
    - assets/3.png
    - assets/categories/tshirt.png
    - assets/categories/shoe.png
    - assets/categories/accessories.png
    - assets/categories/dress.png
    - assets/categories/informal.png
    - assets/categories/jeans.png

